apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torrent-client
spec:
  ingressClassName: traefik
  rules:
    # to be accessed from LAN/VPN only
    - host: torrent.milanoid.net # subdomain of my cloudflare domain
      http:
        paths:
          - backend:
              service:
                name: torrent
                port:
                  number: 8080
            path: /
            pathType: Prefix
