apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audiobookshelf # Comment out this line to exclude from deployment
  - linkding       # Comment out this line to exclude from deployment
  - webhosting     # Comment out this line to exclude from deployment
  - downloaders-pvc
  - radarr
  - prowlarr
  - torrent-client
  - bazarr
  - sonarr
  - pihole
